GET http://localhost:8053/persons/by-id?name=Василий&surname=Петров&age=23
Accept: application/json

###
GET http://localhost:8050/persons/by-city?city=MOSCOW
Accept: application/json

###
GET http://localhost:8050/persons/less-age?age=25
Accept: application/json

###
GET http://localhost:8050/persons/by-name-surname?name=Василий&surname=Петров
Accept: application/json

###
